# ai/mock_ai_client.py — Drop-in mock for a real multimodal AI API
#
# To replace with a real model (e.g. EricAI / OpenAI Vision):
#   1. Create a new class that implements the same analyze() signature.
#   2. Pass it to AIWorker instead of MockAIClient.
#   3. main.py requires zero changes.

from __future__ import annotations

import time

from interaction.schemas import AIAnalysisRequest, AIAnalysisResult


class MockAIClient:
    """Simulates a multimodal API call with a fixed 2-second latency."""

    def analyze(self, request: AIAnalysisRequest) -> AIAnalysisResult:
        # Simulate network / inference latency — runs inside AIWorker thread only
        time.sleep(2.0)

        return AIAnalysisResult(
            request_id=request.request_id,
            object_name="Demo Object",
            function="This object is used for demonstration purposes.",
            confidence=0.90,
            short_description="A placeholder result generated by MockAIClient.",
        )
